import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { OnboardingIntercept } from "@/components/OnboardingIntercept";
import { BottomTabBar } from "@/components/BottomTabBar";
import { Sidebar } from "@/components/Sidebar";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <Navbar />
          <div className="flex min-h-[calc(100vh-73px)]">
            <div className="hidden md:block">
              <Suspense fallback={<div className="w-64 h-screen border-r bg-background"></div>}>
                <Sidebar />
              </Suspense>
            </div>
            <div className="flex-1 bg-background pb-20 md:pb-0">
              {children}
            </div>
          </div>
          <BottomTabBar />
          <Toaster />
          <OnboardingIntercept />
        </Providers>
      </body>
    </html>
  );
}
